web:
  build: node-hello
  ports:
    - "3000:3000"
  stdin_open: true
  tty: true
  working_dir: /src
  volumes:
    - ./node-hello:/src

nginx:
  image: nginx
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - web:web
